load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")
load("//mediapipe/framework/port:build_config.bzl", "mediapipe_proto_library")
load("//mediapipe/framework/tool:mediapipe_graph.bzl", "mediapipe_simple_subgraph")

mediapipe_aar(
    name = "mediapipe_face_geometry",
    calculators = ["//mediapipe/modules/face_geometry:face_geometry"],
)
