load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mediapipe_face_geometry",
    calculators = ["//mediapipe/modules/face_geometry:geometry_pipeline_calculator"],
)
