load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mediapipe_face_effect",
    calculators = ["//mediapipe/graphs/face_effect:face_effect_gpu_deps"],
)
